#ifndef DUGLOBALDEFINES_H
#define DUGLOBALDEFINES_H

#define XSIZE 1000.0
#define YSIZE 600.0

#define XBALL XSIZE/2
#define YBALL YSIZE/2
#define WBALL 20
#define HBALL 20
#define VXBALL 2
#define VYBALL 2

#define XPLATFORM XSIZE*1/2
#define YPLATFORM YSIZE*7/8
#define WPLATFORM 100
#define HPLATFORM 10
#define VXPLATFORM 5
#define VYPLATFORM 0

#define MAX_SPEED 12

#define MILISECONDS 10

#endif // DUGLOBALDEFINES_H
